# Generated by Django 5.1.2 on 2024-11-25 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Card', 'Platební karta'), ('Pluxee', 'Pluxee karta'), ('Cash', 'Hotovost')], default='Card', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(choices=[('pieces', 'ks'), ('grams', 'g'), ('mililiters', 'ml'), ('liters', 'l')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('food_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.foodtype')),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.paymentmethod')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.store')),
            ],
        ),
    ]
