# Generated by Django 5.1.2 on 2024-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
